<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SinuGameVault</AssemblyName>
    <RootNamespace>SinuGameVault</RootNamespace>
    <Version>2.1.2</Version>
    <Authors>Sinu Game Vault</Authors>
    <Product>Sinu Game Vault for Windows</Product>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\GameVault.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\GameVault.ico" />
  </ItemGroup>
</Project>
