import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";

const html=fs.readFileSync("index.html","utf8");
const js=fs.readFileSync("app.js","utf8");
const financeJs=fs.readFileSync("finance.js","utf8");
const css=fs.readFileSync("app.css","utf8");
const sw=fs.readFileSync("sw.js","utf8");
const biglyWorker=fs.readFileSync("biglybt-worker/worker.js","utf8");
const manifest=JSON.parse(fs.readFileSync("manifest.webmanifest","utf8"));
const pkg=JSON.parse(fs.readFileSync("package.json","utf8"));
const version=(js.match(/var APP_VERSION\s*=\s*"(\d+\.\d+\.\d+)"/)||[])[1];

assert.match(html,/href="app\.css(?:\?v=\d+\.\d+\.\d+)?"/);
assert.match(html,/src="app\.js(?:\?v=\d+\.\d+\.\d+)?"/);
assert.ok(version,"application version must be present");
assert.equal(pkg.version,version,"package version must match APP_VERSION");
assert.ok(html.includes(`app.css?v=${version}`),"CSS asset version must match APP_VERSION");
assert.ok(html.includes(`app.js?v=${version}`),"JavaScript asset version must match APP_VERSION");
assert.ok(html.includes(`finance.js?v=${version}`),"Finance asset version must match APP_VERSION");
assert.match(html,/viewport-fit=cover/);
assert.match(html,/maximum-scale=1/);
assert.match(html,/user-scalable=no/);
assert.match(css,/safe-area-inset-left/);
assert.match(css,/-webkit-text-size-adjust:100%/);
assert.match(css,/touch-action:pan-x pan-y/);
assert.match(js,/gesturestart/);
assert.match(css,/@media \(max-width:520px\)/);
assert.ok(html.length<50000,"index.html should stay a small application shell");
assert.ok(css.length>10000,"application styles are unexpectedly empty");
assert.ok(js.length>100000,"application script is unexpectedly empty");
new vm.Script(js,{filename:"app.js"});
new vm.Script(financeJs,{filename:"finance.js"});
new vm.Script(sw,{filename:"sw.js"});
const biglyDashboardStart=biglyWorker.indexOf("function nativeDashboardPage() {");
const biglyDashboardEnd=biglyWorker.indexOf("async function nativeRpc",biglyDashboardStart);
assert.ok(biglyDashboardStart>=0&&biglyDashboardEnd>biglyDashboardStart,"BiglyBT native dashboard must be present");
const biglyDashboardFactory=new Function(`${biglyWorker.slice(biglyDashboardStart,biglyDashboardEnd)};return nativeDashboardPage;`)();
const biglyDashboardHtml=biglyDashboardFactory();
const biglyScriptStart=biglyDashboardHtml.indexOf("<script>")+8;
const biglyScriptEnd=biglyDashboardHtml.lastIndexOf("</script>");
assert.ok(biglyScriptStart>=8&&biglyScriptEnd>biglyScriptStart,"BiglyBT dashboard script must be embedded");
new vm.Script(biglyDashboardHtml.slice(biglyScriptStart,biglyScriptEnd),{filename:"biglybt-native-dashboard.js"});
for(const marker of ["gvbt-switch-mode",'data-filter="error"',"historyExport",'id="sort"','id="pasteMagnet"',"navigator.clipboard.readText"]){
  assert.ok(biglyWorker.includes(marker),`BiglyBT dashboard must include ${marker}`);
}
assert.match(js,/function confirmDestructive\(/);
assert.match(js,/function ensureSeriesEpisodeRatings\(/);
assert.match(js,/episode-summary-rating/);
assert.match(js,/home-overview/);
for(const name of ["movieCard","watchlistCard","watchlistSearchCard","seriesCard","seriesSearchCard"]){
  const count=(js.match(new RegExp("function\\s+"+name+"\\s*\\(","g"))||[]).length;
  assert.equal(count,1,`${name} should have one canonical implementation`);
}
for(const asset of ["./index.html","./app.css","./app.js","./finance.js","./manifest.webmanifest"]){
  assert.ok(sw.includes(`"${asset}"`),`service worker must cache ${asset}`);
}
assert.equal(manifest.name,"Sinu Game Vault");
assert.match(html,/name="description"/);
assert.match(html,/property="og:title"/);
assert.match(html,/rel="canonical"/);
assert.match(html,/id="shareBtn"/);
assert.match(js,/function validateVault\(/);
assert.match(js,/function createRecoverySnapshot\(/);
assert.match(js,/var APP_VERSION\s*=/);
assert.match(js,/var APP_VERSION\s*=\s*"\d+\.\d+\.\d+"/);
assert.match(js,/function gameKnownReleaseDate\s*\(/,"Game release dates must remain available across tabs");
assert.match(js,/function gameReleaseMeta\s*\(/,"Games must keep their release-date countdown renderer");
assert.match(js,/game-tile-info[\s\S]*gameReleaseMeta\(x\)/,"Every game grid card must show known release information");
assert.match(js,/if\(m\.date\) return '<div class="media-release">Release date:/,"Film cards in every tab must show known release dates");
assert.match(js,/var countdown=daysBetween\(today\(\),parseD\(date\)\)>=0\?releaseCountdown\(date\)/,"TV Series cards must show future-date countdowns");
assert.match(css,/\.release-countdown\.urgent[\s\S]*\.release-countdown\.soon[\s\S]*\.release-countdown\.later/,"Release countdown color thresholds must remain available");
assert.match(js,/var APP_BUILD_DATE\s*=\s*"\d{4}-\d{2}-\d{2}"/);
assert.match(html,/id="appVersionBadge"/);
assert.match(js,/primary_release_date\.gte/);
assert.match(js,/function pickReleaseEvent\(/);
const upcomingSource=js.match(/function fetchUpHw\([\s\S]*?function pickReleaseEvent/)[0];
assert.match(upcomingSource,/region:\s*"US"/);
assert.match(upcomingSource,/with_release_type:\s*"2\|3"/);
assert.doesNotMatch(upcomingSource,/with_original_language/);
assert.match(js,/var gdUploadQueue=Promise\.resolve\(\)/);
assert.doesNotMatch(sw,/install[\s\S]{0,250}skipWaiting/);
assert.match(sw,/if \(res\.ok\)/);
assert.match(js,/data-bigly="remove-data"/);
assert.doesNotMatch(js,/plot\.length>12000/);
for(const label of ["Movies","TV Shows","Plex Library"]){ assert.ok(html.includes(label),`primary navigation must include ${label}`); }
assert.match(html,/data-section="finance"/);
assert.match(financeJs,/gamevault-finance-v1/);
assert.match(financeJs,/AES-GCM/);
assert.match(financeJs,/PBKDF2/);
assert.ok(financeJs.includes("function financeIsCardAccount"),"card accounts must be classifiable");
assert.ok(financeJs.includes('kind==="income"&&financeIsCardAccount'),"card credits must never count as income");
assert.ok(financeJs.includes("Top 10 merchants"),"overview must rank top merchants by usage");
assert.match(financeJs,/extensions:\{prf:/);
assert.match(financeJs,/function financeShouldAutoUnlock\(/);
assert.match(financeJs,/if\(financeBusy\)\{financeTouch\(\);return;\}/);
assert.doesNotMatch(financeJs,/capability\.then\(/);
assert.match(financeJs,/vaultSalt:data\.finance\.salt/);
assert.match(financeJs,/FINANCE_DEVICE_DB/);
assert.match(financeJs,/function financeDeviceKey\(/);
assert.match(financeJs,/mode:parts\[2\]/);
assert.match(financeJs,/finance-pin-show/);
assert.match(financeJs,/FINANCE_LOCK_PREF/);
assert.match(financeJs,/finance-import-confirm/);
assert.match(financeJs,/https:\/\/www\.googleapis\.com\/auth\/gmail\.readonly/);
assert.match(financeJs,/function financeGmailSync\(/);
assert.match(financeJs,/function financeGmailListMessages\(/);
assert.match(financeJs,/function financeGmailQuery\(/);
assert.match(financeJs,/function financeMapLimit\(/);
assert.match(financeJs,/function financeGmailBatchSize\(\)\{return phoneUi\(\)\?6:30;\}/);
assert.match(financeJs,/function financeGmailConcurrency\(\)\{return phoneUi\(\)\?1:2;\}/);
assert.match(financeJs,/initialBackfillComplete/);
assert.match(financeJs,/retryMessageIds/);
assert.match(financeJs,/importedStatementKeys/);
assert.match(financeJs,/function financeGmailReadMessage\(/);
assert.match(financeJs,/function financeGmailEmi\(/);
assert.match(financeJs,/function financeMonthStats\(/);
assert.match(financeJs,/function financeRecurring\(/);
assert.match(financeJs,/function financeKind\(/);
assert.match(financeJs,/finance-toggle-detail/);
assert.match(financeJs,/STATEMENT-ONLY DATA SOURCE/);
assert.match(financeJs,/has:attachment/);
assert.match(financeJs,/subject:\"credit card statement\"/);
assert.match(financeJs,/subject:\"bank statement\"/);
assert.match(financeJs,/function financeGmailIsStatement\(/);
assert.ok(!financeJs.includes("var alert=financeGmailAlertTransaction"),"Statement sync must not import individual Gmail transaction alerts");
assert.match(financeJs,/financeGmailAutoBlocked/);
assert.match(financeJs,/financeGmailSetupRequired/);
assert.match(financeJs,/Enable Gmail API/);
assert.ok(!financeJs.includes('data-act="finance-add-transaction"'),"Finance must not expose manual transaction entry");
assert.ok(!financeJs.includes('data-act="finance-add-loan"'),"Finance must not expose manual loan entry");
assert.match(financeJs,/importedMessageIds/);
assert.match(financeJs,/Access tokens stay only in memory/);
assert.match(css,/\.finance-gmail/);
assert.match(css,/\.finance-auth/);
for(const key of ["serieswatching","seriesnew","seriesupcoming","enseries","mlseries","taseries","hiseries"]){ assert.ok(js.includes(key),`TV navigation must include ${key}`); }
assert.match(js,/watchingSeries/);
assert.match(js,/PLEX_ORDER=\["home","continue","movies","shows","recent"\]/);
assert.match(html,/id="desktopRailBtn"/);
assert.match(html,/id="commandPalette"/);
assert.match(css,/@media \(min-width:900px\)/);
assert.match(css,/html:not\(\.tv\) \.sectionsw/);
assert.match(js,/function openCommandPalette\(/);
assert.match(js,/function applyDesktopShell\(/);
assert.match(js,/document\.body\.classList\.remove\("command-open"\)/);
assert.match(js,/function moviePrimaryAction\(/);
assert.match(js,/function seriesPrimaryAction\(/);
assert.match(js,/function applyMediaSort\(/);
assert.match(html,/id="desktopRailSync"/);
assert.match(css,/\.title-menu-pop/);
assert.match(html,/class="hamburger-icon"/);
assert.match(js,/function detailToolbar\(/);
assert.match(js,/var SERIES_ORDER=\["serieswatchlist","serieswatching","seriesnew","seriesupcoming","enseries","mlseries","taseries","hiseries","serieswatched"\]/);
assert.match(js,/window\.gameVaultTvKey=tvHandleTvKey/);
assert.match(js,/function renderTvApp\(/);
assert.match(js,/function tvRowsForSection\(/);
assert.match(js,/function tvHeroHtml\(/);
assert.match(js,/function tvHomeSummaryHtml\(/);
assert.match(js,/function tvRowLayout\(/);
assert.match(js,/function tvHandleShellKey\(/);
assert.match(css,/\.tv-shell/);
assert.match(css,/\.tv-card-row/);
assert.match(css,/\.tv-feature-hero/);
assert.match(css,/\.tv-home-summary/);
assert.match(css,/\.tv-rail:focus-within/);
assert.match(js,/\["biglybt","⇩","Downloads"\]/);
assert.match(js,/if\(TV_MODE\)\{worker\.postMessage\(\{type:"SKIP_WAITING"\}\);return;\}/);
assert.match(js,/summary,\[role="button"\]/);
assert.doesNotMatch(js,/window\.innerHeight\*\.48/);
assert.match(js,/id=\"tvGdQrBox\"/);
assert.match(js,/data-tv-system=\"drive-login\"/);
assert.match(js,/data-tv-system=\"drive-save\"/);
assert.match(css,/\.tv-drive-setup button\{grid-column:1\/-1/);
assert.match(css,/\.tv-drive-login\{display:grid;grid-template-columns:minmax\(0,1fr\)/);
assert.match(css,/\.tv-drive-qr\{position:fixed;z-index:100/);
assert.match(js,/data-tv-key=\"qr:cancel\"/);
assert.match(sw,/gamevault-shell-v\d+/);
assert.match(js,/function scheduleMediaWarmup\(/);
assert.match(js,/function scheduleGameWarmup\(/);
assert.match(js,/function pooledEach\(/);
assert.match(js,/function filmCacheKey\(/);
assert.match(js,/function seriesCacheKey\(/);
assert.match(sw,/cachedPromise/);
assert.match(sw,/gamevault-images-v1/);
assert.match(js,/function warmVisibleContent\(/);
assert.match(js,/function refreshAllData\(/);
assert.match(js,/function plexDetailPage\(/);
assert.match(js,/data-act=\"plex-open\"/);
assert.doesNotMatch(js,/if\(!item\|\|!item\.watched\) return/);
assert.ok(biglyWorker.includes("recordHistory(t,'Completed',false)"),"completed downloads must be recorded to history");
assert.ok(biglyWorker.includes("data-hdelete="),"history must offer delete torrent + files");
assert.ok(biglyWorker.includes("'delete-local-data':true"),"history delete must permanently remove local data");
assert.ok(!biglyWorker.includes("data-hremove"),"history records must not be removable");
assert.match(biglyWorker,/id="historyView"/);
assert.match(biglyWorker,/Manually removed before completion/);
assert.match(js,/function plexReconcilePlayback\(/);
assert.match(js,/watchingMovies/);
assert.match(js,/function gdRefreshUsage\(/);
assert.match(html,/data-section="health"/);
assert.match(js,/function renderHealth\(/);
assert.match(js,/healthfood/);
assert.match(js,/function vaultCopyForCloud\(/);
assert.match(js,/delete copy\.keys/);
assert.match(js,/if\(!healthCloudSyncEnabled\(\)\) delete copy\.health/);
assert.match(html,/id="healthCloudInput"/);
assert.doesNotMatch(js,/Absolute eosinophils were/);
console.log("GameVault smoke checks passed");
