import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";

const html=fs.readFileSync("index.html","utf8");
const js=fs.readFileSync("app.js","utf8");
const css=fs.readFileSync("app.css","utf8");
const sw=fs.readFileSync("sw.js","utf8");
const manifest=JSON.parse(fs.readFileSync("manifest.webmanifest","utf8"));

assert.match(html,/href="app\.css(?:\?v=\d+\.\d+\.\d+)?"/);
assert.match(html,/src="app\.js(?:\?v=\d+\.\d+\.\d+)?"/);
assert.match(html,/viewport-fit=cover/);
assert.match(html,/maximum-scale=1/);
assert.match(html,/user-scalable=no/);
assert.match(css,/safe-area-inset-left/);
assert.match(css,/-webkit-text-size-adjust:100%/);
assert.match(css,/touch-action:pan-x pan-y/);
assert.match(js,/gesturestart/);
assert.match(css,/@media \(max-width:520px\)/);
assert.ok(html.length<50000,"index.html should stay a small application shell");
assert.ok(css.length>10000,"application styles are unexpectedly empty");
assert.ok(js.length>100000,"application script is unexpectedly empty");
new vm.Script(js,{filename:"app.js"});
new vm.Script(sw,{filename:"sw.js"});
for(const name of ["movieCard","watchlistCard","watchlistSearchCard","seriesCard","seriesSearchCard"]){
  const count=(js.match(new RegExp("function\\s+"+name+"\\s*\\(","g"))||[]).length;
  assert.equal(count,1,`${name} should have one canonical implementation`);
}
for(const asset of ["./index.html","./app.css","./app.js","./manifest.webmanifest"]){
  assert.ok(sw.includes(`"${asset}"`),`service worker must cache ${asset}`);
}
assert.equal(manifest.name,"Sinu Game Vault");
assert.match(js,/function validateVault\(/);
assert.match(js,/function createRecoverySnapshot\(/);
assert.match(js,/var APP_VERSION\s*=/);
assert.match(js,/var APP_VERSION\s*=\s*"\d+\.\d+\.\d+"/);
assert.match(js,/var APP_BUILD_DATE\s*=\s*"\d{4}-\d{2}-\d{2}"/);
assert.match(html,/id="appVersionBadge"/);
assert.match(js,/primary_release_date\.gte/);
assert.match(js,/function pickReleaseEvent\(/);
const upcomingSource=js.match(/function fetchUpHw\([\s\S]*?function pickReleaseEvent/)[0];
assert.match(upcomingSource,/region:\s*"US"/);
assert.match(upcomingSource,/with_release_type:\s*"2\|3"/);
assert.doesNotMatch(upcomingSource,/with_original_language/);
assert.match(js,/var gdUploadQueue=Promise\.resolve\(\)/);
assert.doesNotMatch(sw,/install[\s\S]{0,250}skipWaiting/);
assert.match(sw,/if \(res\.ok\)/);
assert.match(js,/data-bigly="remove-data"/);
assert.doesNotMatch(js,/plot\.length>12000/);
for(const label of ["Movies","TV Shows","Plex Library"]){ assert.ok(html.includes(label),`primary navigation must include ${label}`); }
for(const key of ["serieswatching","seriesnew","seriesupcoming","enseries","mlseries","taseries","hiseries"]){ assert.ok(js.includes(key),`TV navigation must include ${key}`); }
assert.match(js,/watchingSeries/);
assert.match(js,/PLEX_ORDER=\["home","continue","movies","shows","recent"\]/);
assert.match(html,/id="desktopRailBtn"/);
assert.match(html,/id="commandPalette"/);
assert.match(html,/app\.css\?v=1\.10\.0/);
assert.match(html,/app\.js\?v=1\.12\.0/);
assert.match(css,/@media \(min-width:900px\)/);
assert.match(css,/html:not\(\.tv\) \.sectionsw/);
assert.match(js,/function openCommandPalette\(/);
assert.match(js,/function applyDesktopShell\(/);
assert.match(js,/document\.body\.classList\.remove\("command-open"\)/);
assert.match(js,/function moviePrimaryAction\(/);
assert.match(js,/function seriesPrimaryAction\(/);
assert.match(js,/function applyMediaSort\(/);
assert.match(html,/id="desktopRailSync"/);
assert.match(css,/\.title-menu-pop/);
assert.match(html,/class="hamburger-icon"/);
assert.match(js,/function detailToolbar\(/);
assert.match(js,/var SERIES_ORDER=\["serieswatchlist","serieswatching","seriesnew","seriesupcoming","enseries","mlseries","taseries","hiseries","serieswatched"\]/);
assert.match(js,/window\.gameVaultTvKey=tvHandleTvKey/);
assert.match(js,/function renderTvApp\(/);
assert.match(js,/function tvRowsForSection\(/);
assert.match(js,/function tvHandleShellKey\(/);
assert.match(css,/\.tv-shell/);
assert.match(css,/\.tv-card-row/);
assert.match(js,/summary,\[role="button"\]/);
assert.doesNotMatch(js,/window\.innerHeight\*\.48/);
assert.match(js,/id=\"tvGdQrBox\"/);
assert.match(js,/data-tv-system=\"drive-login\"/);
assert.match(js,/data-tv-system=\"drive-save\"/);
assert.match(css,/\.tv-drive-setup button\{grid-column:1\/-1/);
assert.match(css,/\.tv-drive-login\{display:grid;grid-template-columns:minmax\(0,1fr\)/);
assert.match(css,/\.tv-drive-qr\{position:fixed;z-index:100/);
assert.match(js,/data-tv-key=\"qr:cancel\"/);
assert.match(sw,/gamevault-shell-v35/);
assert.match(js,/function plexDetailPage\(/);
assert.match(js,/data-act=\"plex-open\"/);
assert.doesNotMatch(js,/if\(!item\|\|!item\.watched\) return/);
const biglyWorker=fs.readFileSync("biglybt-worker/worker.js","utf8");
assert.match(biglyWorker,/Remove completed: On/);
assert.match(biglyWorker,/delete-local-data':false/);
assert.match(biglyWorker,/id="historyView"/);
assert.match(biglyWorker,/Manually removed before completion/);
assert.match(js,/function plexReconcilePlayback\(/);
assert.match(js,/watchingMovies/);
assert.match(js,/function gdRefreshUsage\(/);
assert.match(html,/data-section="health"/);
assert.match(js,/function renderHealth\(/);
assert.match(js,/healthfood/);
assert.match(js,/labDate==="2026-07-11"/);
console.log("GameVault smoke checks passed");
